# File required to load packs as NeoForge mods.
# Find more information on toml format v0.5.0 here:  https://github.com/toml-lang/toml

# NeoForge settings
modLoader="javafml"
loaderVersion="[4,)"

# The license for your pack. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]] 
# The ID of your pack.
modId="mtsofficialpack"
# Version number.  Must start with a number or Forge complains.
version="28"
 # Display name for the pack in the in-game mods list.
displayName="Immersive Vehicles (MTS/IV) - Official Content Pack"
# A URL for the "homepage" for this pack, displayed in the mod UI.
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-transport-simulator"
# Pack logo.
logoFile="vingette.png"
# The description text for the pack (multi line!)
description='''
A small selection of content made by the core Immersive Vehicles (MTS) team.  This pack aims to show a little of all the things the mod can do, but not focus in any one area too heavily.  A good all-around starter pack.

Credits go to Mr.Mulle, Conman180, Cactus & BlazeWolf1122.
'''

[[dependencies.mtsofficialpack]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mtsofficialpack]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mtsofficialpack]]
    modId="mts"
    type="required"
    versionRange="[22.18.0,)"
    ordering="NONE"
    side="BOTH"
